### ISSUE TITLE
Oppstarts-script

### ISSUE THREAD

**Issue by julian-ao** [appKom/infoskjerm#106]
Fiks slik at rasperry pi'en åpner inforskjermen ved oppstart.

Jøgga mente dette var ganske enkelt å fikse. Han meldte også at det var mulig å sette rasberry pi'en i "kiosk"-modus som  gjorde at infoskjerm-nettsiden er alt som går ann å vises på skjermen.

**Comment by jorgengaldal** [comment]
https://www.raspberrypi.com/tutorials/how-to-use-a-raspberry-pi-in-kiosk-mode/

**Comment by julian-ao** [comment]
> https://www.raspberrypi.com/tutorials/how-to-use-a-raspberry-pi-in-kiosk-mode/

Noe du har lyst til å se på @jorgengaldal ?
