### ISSUE TITLE
Bare vis én logo om gangen

### ISSUE THREAD

**Issue by julian-ao** [appKom/infoskjerm#132]
Istedenfor å vise online og bekk logoen samtidig, kunne det vært en ide å bytte på hvilke logoer som vises. 10 sek hver ellerno.

![image](https://github.com/user-attachments/assets/b3ff099d-2041-459e-9bd5-34716cf9a470)

**Comment by jorgengaldal** [comment]
Hvorfor det, tenker du? Er det ikke plass til dem begge?

**Comment by julian-ao** [comment]
Jo det er vel egt det. Tanken var å bare ikke vise for mye av gangen.

**Comment by jorgengaldal** [comment]
Skjønner! Personlig tenker jeg at det ser greit ut sånn som det er nå.

**Comment by julian-ao** [comment]
Prøver å få plass til debug QR kode også:

![image](https://github.com/user-attachments/assets/df43e88e-110b-4f2e-b938-d6c580db62e7)

**Comment by julian-ao** [comment]
> Hva synes du om denne: https://infoskjerm-git-132-logo-appkom.vercel.app/

Lov å si at det ikke funka @jorgengaldal hahaha

**Comment by jorgengaldal** [comment]
Ser jo at det kan bli litt mer cramped hvis man prøver å få inn andre ting i headeren også. Synes demoen virket nice (kunne kanskje vært litt kortere tid mellom byttene), men ville hørt med prokom om det er innafor at vi bytter logoene slik. Kan tenkes at vi ikke får lov med tanke på grafisk profil og eventuelt med tanke på hovedsamarbeidsavtalen.

**Comment by jorgengaldal** [comment]
Haha, var ikke meningen å ikke svare, ble bare distrahert av at jeg prøvde å finne frem hovedsamarbeidsavtalen.

**Comment by julian-ao** [comment]
Kan høre med prokom
