### ISSUE TITLE
Reduser tiden på VideoPage

### ISSUE THREAD

**Issue by jorgengaldal** [appKom/infoskjerm#141]
Synes personlig at infoskjermen er altfor ofte på video. Hadde det vært en mulighet å heller la den komme litt sjeldnere (så blir den også mer spesiell når den kommer)?

**Comment by julian-ao** [comment]
Vi kan fikse noe sånt ja, feks legge til flere event- og slack-sider før videoPage kommer:
![image](https://github.com/user-attachments/assets/3578ba2e-3ccb-40ac-8645-8b9278c8c6bf)

![image](https://github.com/user-attachments/assets/14e1585a-cbf5-4429-9293-64d80c6a6cb1)
